### ISSUE TITLE
Tutorial: tracing code

### ISSUE THREAD

**Issue by vigneshsankariyer1234567890** [AY2122S1-CS2103T-W15-4/tp#1]
Here is a trace of the add and edit commands:

<img width="1440" alt="Screenshot 2021-09-27 at 5 40 36 PM" src="https://user-images.githubusercontent.com/68676914/134888401-c13a90cf-4085-4bad-a9b8-584fa384c671.png">
<img width="1440" alt="Screenshot 2021-09-27 at 5 41 47 PM" src="https://user-images.githubusercontent.com/68676914/134888422-1d2637dc-4c2f-415a-a27a-4c8a01718a85.png">
<img width="1440" alt="Screenshot 2021-09-27 at 5 44 26 PM" src="https://user-images.githubusercontent.com/68676914/134888431-7e0b76eb-dc7b-4fcf-8826-6e5272a601f1.png">
<img width="1440" alt="Screenshot 2021-09-27 at 5 49 04 PM" src="https://user-images.githubusercontent.com/68676914/134888438-e972440a-a4d6-46f0-99a6-a8bcea3154a0.png">
<img width="1440" alt="Screenshot 2021-09-27 at 5 52 20 PM" src="https://user-images.githubusercontent.com/68676914/134888445-866fec3c-b045-403e-8e5e-9a267f73026c.png">
<img width="1440" alt="Screenshot 2021-09-27 at 5 54 47 PM" src="https://user-images.githubusercontent.com/68676914/134888448-e4fcdea8-fccc-414c-a210-59e32701890c.png">

**Comment by gok99** [comment]
Thanks! Am closing this issue since no further follow-up is required
