### ISSUE TITLE
[PE-D] tagrm command not working as intended

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#125]
Added tag to Charlotte and calling tagrm but with an upper case in the name field.

![image.png](https://raw.githubusercontent.com/cheweejia/ped/main/files/c9dcfb11-680c-43c0-bf8f-f0432ad91471.png)

Expected result: Either the tag is removed since it is case-insensitive, or the tag isnt removed since it is case sensitive.

Actual result:

It says tag removed but the tag remains.

![image.png](https://raw.githubusercontent.com/cheweejia/ped/main/files/4e3d3b6c-b345-4cb0-b838-3bed44e64baf.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: cheweejia/ped#9

**Comment by gok99** [comment]
the tag name does not exitst ('Testing' is the tag value). So, tag removed is vacuously true... but will think about how to make this clearer
