### ISSUE TITLE
[PE-D] Format of command in the error message differs from the UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#129]
![image.png](https://raw.githubusercontent.com/TohWeiJie01/ped/main/files/2a213f0f-9cad-46af-b600-d985c5233d4e.png)

Similar to the earlier bug reported, the edit command message has a different format from that of the UG. Even though both variants of the input format works, it might be better to just standardise to avoid confusion but having the error message reflect the spacing between the prefix and input.

Edit: Since all the error messages probably have the same issue, I'll just indicate that in this bug so that I won't create a bunch of nitpicky issues regarding this error message format.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: TohWeiJie01/ped#5

**Comment by lhw-1** [comment]
Resolved by #152
