### ISSUE TITLE
[PE-D] Edit Command: not all tags cleared

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#133]
![Screenshot 2021-10-29 at 5.03.37 PM.png](https://raw.githubusercontent.com/tsinyee/ped/main/files/190bc7af-163e-4f6d-9f1e-563c772fb289.png)
Steps to reproduce: `edit 1 -t  ` <br>
is `INCOMPLETE `/ `COMPLETE` a tag?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tsinyee/ped#9

**Comment by vigneshsankariyer1234567890** [comment]
I guess we should explicitly state that every person would have a completion status tag in UG. Documentation error

**Comment by lhw-1** [comment]
Resolved by #152
