### ISSUE TITLE
[PE-D] Unexpected result after usage of the find command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#136]
![image.png](https://raw.githubusercontent.com/TohWeiJie01/ped/main/files/ff913db3-971f-4805-a20d-e20709bd9fb0.png)

There seems to be instances where the list command does not work. In this case, I first inputted find Charlotte and the app gives me the correct result. However, after that, I inputted list as the next command and the app ended up giving the above list. Notice that there are two copies of the Charlotte entry despite this not being in the list before and not possible to have two copies of the same person in the address book. Moreover, the entries for 2 and 4 just doesn't show up.

Edit: The app generally seems unresponsive to anything but the same find input. After several tries of inputting several different commands to no avail, I attempted to input a wrong format of the find command and then tried list again and the end result was as such:

![image.png](https://raw.githubusercontent.com/TohWeiJie01/ped/main/files/d8b4643f-9e76-4bcd-802f-bf1e9745f5ec.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: TohWeiJie01/ped#7

**Comment by vigneshsankariyer1234567890** [comment]
Could it be something to do with state manager? need to inspect how does find work.

**Comment by gok99** [comment]
Unable to reproduce
