### ISSUE TITLE
[PE-D] Clearing data and exporting causes data to reappear

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#137]
After `clear`, following with an `export` causes the data to reappear.

Steps to reproduce included in video:

[IMG_20211029_172449_705_01.mp4](https://raw.githubusercontent.com/atyhamos/ped/main/files/74b8a3d8-964f-420e-8700-af066b175e8a.mp4)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: atyhamos/ped#14

**Comment by vigneshsankariyer1234567890** [comment]
probably has to do with state manager. in this case, 
1) clear should place an empty address book on top, and 
2) export should also hence create another empty addressbook and 
3) add it to the top until yes command given. 
4) after which, it should revert to empty addressbook state in 1)

**Comment by vigneshsankariyer1234567890** [comment]
Solution: either add a dummy state or just decouple export and history manager completely
