### ISSUE TITLE
[PE-D] Undo command not mentioned in the User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#139]
Application features an `undo` command, but is not mentioned in the User Guide.

![image.png](https://raw.githubusercontent.com/atyhamos/ped/main/files/935a3727-6716-4925-bcf5-5218f38d3721.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: atyhamos/ped#15

**Comment by lhw-1** [comment]
Resolved by #152
