### ISSUE TITLE
[PE-D] Purpose of icon next to phone number in each entry

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#142]
I don't quite understand what is the purpose of the icon next to each phone number in each feature.

![image.png](https://raw.githubusercontent.com/TohWeiJie01/ped/main/files/2393973b-e29e-4153-be14-e38f94ecb5ba.png)

They seem to be clickable, but it does nothing. Moreover, there is no mention of it anywhere in the UG.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: TohWeiJie01/ped#9

**Comment by lhw-1** [comment]
Resolved by #152
