### ISSUE TITLE
[PE-D] Image in UG is not updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#146]
The accompanying image in the UG for Find is not updated to reflect the current look of the product.

![image.png](https://raw.githubusercontent.com/TohWeiJie01/ped/main/files/6e6368a5-a4fb-46dd-96fe-6d6c3b31bb2d.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: TohWeiJie01/ped#10

**Comment by lhw-1** [comment]
Duplicate of Issue #104.
