### ISSUE TITLE
[PE-D] Progress bar in each entry

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#149]
![image.png](https://raw.githubusercontent.com/TohWeiJie01/ped/main/files/bd752eaf-40d0-4f7e-8d3b-8fe83cf55aa4.png)

Similar to the pie chart, I feel like the progress bar feels underutilised. Right now, a person in the app can be either Complete or Incomplete, and if that are complete the progress bar is filled up and if they are not the progress bar is empty. In that case, if the completion of a person is already indicated as a tag, it seems redundant to have a progress bar as well that takes up more space in the UI just for essentially the same purpose.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: TohWeiJie01/ped#12

**Comment by lhw-1** [comment]
Not a feature flaw, documentation was not clear that `ONGOING` is a possible status.

**Comment by gok99** [comment]
Possibly can have more increments

**Comment by lhw-1** [comment]
Resolved by #152
