### ISSUE TITLE
[PE-D] Incomplete Command Summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-4/tp#150]
![image.png](https://raw.githubusercontent.com/TohWeiJie01/ped/main/files/9a94f8b9-720e-4098-ac33-1e6878bdc4f1.png)

The Command Summary in the UG also is missing a large portion of the commands you guys support for your app. Don't forget to update it!

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: TohWeiJie01/ped#13

**Comment by lhw-1** [comment]
Resolved by #152
